disp("Frobenius distance between the two laplacian matrices we computed:");

urls = askUserForMultipleOFFfiles();
for url = urls
    mesh = Mesh(url{1});
    disp([...
        mesh.Name, ...
        ": ", ...
        norm(mesh.Laplacian - LaplacianByCotFormula(mesh), 'fro') ...
        ]);
end
